=== KhronosGroup/OpenCOLLADA/xsd2cppsax/tests/validation_simple_types/t05.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	About COLLADA 1.5 sidref_type pattern.
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.netallied.de/xsd2cppsax/tests"
	xmlns="http://www.netallied.de/xsd2cppsax/tests"
	elementFormDefault="qualified">

	<xs:element name="root" type="RootType"></xs:element>

	<xs:complexType name="RootType">
		<xs:sequence>
			<xs:element name="sid" type="sidref_type" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="sidref_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="(([\i-[:]][\c-[:]]*)|.)(/[\i-[:\.]][\c-[:]]*)+((\.[\i-[:]][\c-[:]]*)|(\([0-9]+\)){1,2})?"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== KhronosGroup/OpenCOLLADA/xsd2cppsax/tests/validation_simple_types/t05.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.netallied.de/xsd2cppsax/tests"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.netallied.de/xsd2cppsax/tests t05.xsd"
      >

	<sid>l_hip/rotateY.ANGLE</sid>
	<sid>here/rot(3)</sid>
	<sid>here/mat(3)(2)</sid>
	<sid>./foo.bar</sid>
	<sid>foo/bar/foobar.X</sid>
	<sid>foo/bar</sid>

	<!-- invalid -->
	<sid>1foo/bar.X</sid>
	<sid>foo/1bar.X</sid>
	<sid>:foo/bar.X</sid>
	<sid>foo/:bar.X</sid>
	<sid>fo:o/bar.X</sid>
	<sid>foo/ba:r.X</sid>
	<sid>foo</sid>
	<sid>foo.X</sid>
	<sid>:</sid>

</root>
